# Generated by Django 5.2.14 on 2026-06-19 22:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('esi', '0013_squashed_0012_fix_token_type_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access the Moon Ore Tax user dashboard'), ('staff_access', 'Can access the Moon Ore Tax staff dashboard'), ('admin_access', 'Can access the Moon Ore Tax admin tab (token setup & configuration)')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Flat per-ore tax fraction used when an ore has no explicit OreTaxRate.', max_digits=5)),
                ('despawn_hours', models.PositiveIntegerField(default=48, help_text='Hours after fracture before a pop is finalized (ore field despawns).')),
                ('fuel_low_days', models.PositiveIntegerField(default=7, help_text='Highlight a structure when fuel remaining is under this many days.')),
                ('reminder_every_days', models.PositiveIntegerField(default=2, help_text='Reminder interval (days) while an unpaid invoice is still young.')),
                ('reminder_daily_after_days', models.PositiveIntegerField(default=7, help_text='Once an unpaid invoice is older than this many days, remind daily.')),
                ('target_corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('target_corporation_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='EveName',
            fields=[
                ('eve_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_arrival_time', models.DateTimeField(help_text='readyTime — chunk ready to fracture; anchors attribution windows.')),
                ('auto_fracture_time', models.DateTimeField(blank=True, help_text='autoTime — natural fracture.', null=True)),
                ('ore_volume_by_type', models.JSONField(blank=True, default=dict, help_text='oreVolumeByType: {type_id: volume} chunk total.')),
                ('started_notification_id', models.BigIntegerField(blank=True, null=True)),
                ('fracture_time', models.DateTimeField(blank=True, help_text='The pop: when the chunk actually fractured.', null=True)),
                ('fracture_type', models.CharField(blank=True, choices=[('laser', 'Manual (laser)'), ('auto', 'Automatic')], max_length=8)),
                ('fracture_notification_id', models.BigIntegerField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-chunk_arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('moon_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('system_id', models.BigIntegerField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OreTaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_type_id', models.BigIntegerField(unique=True)),
                ('ore_type_name', models.CharField(blank=True, max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
            options={
                'ordering': ['ore_type_name', 'ore_type_id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessedNotification',
            fields=[
                ('notification_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('notification_type', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('emitted', 'Emitted'), ('payment_sent', 'Payment sent'), ('payment_accepted', 'Payment accepted'), ('marked_paid', 'Marked paid'), ('condoned', 'Condoned')], default='emitted', max_length=20)),
                ('emitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('last_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='moontax.extraction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moontax_invoices', to=settings.AUTH_USER_MODEL)),
                ('moon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moontax.moon')),
            ],
            options={
                'ordering': ['-emitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('mark_paid', 'Marked paid'), ('condone', 'Condoned'), ('delete_payment', 'Deleted payment'), ('note', 'Note')], default='note', max_length=20)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='moontax.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='extraction',
            name='moon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='moontax.moon'),
        ),
        migrations.CreateModel(
            name='PaymentContract',
            fields=[
                ('contract_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contract_type', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('issuer_id', models.BigIntegerField(blank=True, null=True)),
                ('issuer_name', models.CharField(blank=True, max_length=255)),
                ('assignee_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('location_id', models.BigIntegerField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('date_issued', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('offered_items', models.JSONField(blank=True, default=list)),
                ('has_requested_items', models.BooleanField(default=False)),
                ('items_fetched', models.BooleanField(default=False)),
                ('last_mismatch_notified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_contracts', to='moontax.invoice')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structure_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('system_id', models.BigIntegerField(blank=True, null=True)),
                ('system_name', models.CharField(blank=True, max_length=255)),
                ('type_id', models.BigIntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, max_length=255)),
                ('fuel_expires', models.DateTimeField(blank=True, null=True)),
                ('has_moon_drilling', models.BooleanField(default=False)),
                ('drill_state', models.CharField(blank=True, max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structures', to='moontax.moon')),
            ],
            options={
                'ordering': ['name', 'structure_id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moontax.structure'),
        ),
        migrations.AddField(
            model_name='extraction',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='moontax.structure'),
        ),
        migrations.CreateModel(
            name='TokenConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.BigIntegerField(blank=True, null=True)),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('corporation_name', models.CharField(blank=True, max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='esi.token')),
            ],
            options={
                'verbose_name': 'token configuration',
            },
        ),
        migrations.CreateModel(
            name='UnmatchedMiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_id', models.BigIntegerField()),
                ('character_id', models.BigIntegerField()),
                ('character_name', models.CharField(blank=True, max_length=255)),
                ('ore_type_id', models.BigIntegerField()),
                ('recorded_date', models.DateField()),
                ('quantity', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moontax.structure')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore_type_id', models.BigIntegerField()),
                ('ore_type_name', models.CharField(blank=True, max_length=100)),
                ('units_owed', models.BigIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='moontax.invoice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice', 'ore_type_id'), name='moontax_invoiceitem_uniq')],
            },
        ),
        migrations.CreateModel(
            name='MiningLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_id', models.BigIntegerField()),
                ('character_id', models.BigIntegerField()),
                ('ore_type_id', models.BigIntegerField()),
                ('recorded_date', models.DateField(help_text='Ledger day (UTC), derived from last_updated.')),
                ('quantity', models.BigIntegerField(default=0)),
                ('recorded_corporation_id', models.BigIntegerField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_rows', to='moontax.structure')),
            ],
            options={
                'indexes': [models.Index(fields=['recorded_date'], name='moontax_min_recorde_af499d_idx'), models.Index(fields=['character_id', 'recorded_date'], name='moontax_min_charact_e9f775_idx'), models.Index(fields=['observer_id', 'recorded_date'], name='moontax_min_observe_d8c4ba_idx')],
                'constraints': [models.UniqueConstraint(fields=('observer_id', 'character_id', 'ore_type_id', 'recorded_date'), name='moontax_ledger_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('user', 'extraction'), name='moontax_invoice_user_pop_uniq'),
        ),
        migrations.AddConstraint(
            model_name='extraction',
            constraint=models.UniqueConstraint(fields=('structure', 'chunk_arrival_time'), name='moontax_extraction_uniq'),
        ),
        migrations.AddIndex(
            model_name='unmatchedminer',
            index=models.Index(fields=['recorded_date'], name='moontax_unm_recorde_30db6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='unmatchedminer',
            constraint=models.UniqueConstraint(fields=('observer_id', 'character_id', 'ore_type_id', 'recorded_date'), name='moontax_unmatched_uniq'),
        ),
    ]
